@startuml help
help themes
@enduml

@startuml hangmanCMD
!theme cyborg-outline
@startmd todo
 '#FIXME Update Diagram to reflect "main" Diagram created using external Tool 
    @see r"./Hangman UML Diagram.eddx"
    @see r"./Hangman UML Diagram.png"
@endmd

class Hangman{
    -string begriff
    -char[] fehler
    -char[] richtig
    -string versuch

    +int getFehler()
    +char[] getFehler()
    +void neuesWort()
    -char getInput()
    -void inputValidieren(char input)
    -void updateVersuch()
}


'file words{<<words.txt>>}
'hangman --> words : use

@enduml
